import sys
sys.path.append("/home3/alejandro.rodriguez/python_modules")

from functions import *
import json
import torch
from torch_geometric.data import Data
from torch_geometric.nn import knn_graph
from concurrent.futures import ThreadPoolExecutor

# ==============================================================================
# MAIN CONFIGURATION
# ==============================================================================
LABEL           = "KL0" # MUON, KL0, or SIGNAL

#muon, 30011001 (bkg); KL0, 38000800 (bkg); signal, 40114060
IS_SIGNAL       = 0 if LABEL in ["MUON", "KL0"] else 1
DEC_ID          = "30011001" if LABEL == "MUON" else "38000800" if LABEL == "KL0" else "SIGNAL"
INPUT_FILE_NAME = "ntuple_background_30011001.root"
INPUT_FILE_NAME = "ntuple_" + ("signal_40114060.root" if IS_SIGNAL else f"background_{DEC_ID}.root")

INPUT_FILE_PATH = "/lustre/LHCb/alejandro.rodriguez/script_emilio_hits/"
OUTPUT_DIR      = "/lustre/LHCb/alejandro.rodriguez/torch_data"

# Variables to extract from ROOT
VAR_NAMES = [
    'eventNumber', 'x', 'y', 'z', 'n_pix', 'module', 
    'nVtx_per_event', 'nClu_per_event', 'nTrk_per_event'
]
TREE_NAME = "VeloMultiTuple_73eaa531/Clusters"
FULL_PATH = f"{INPUT_FILE_PATH}{INPUT_FILE_NAME}:{TREE_NAME}"

K_NEIGHBOURS = 5 
N_WORKERS    = 16 # Number of parallel threads for graph construction  

# ==============================================================================
# LOAD STATISTICS
# ==============================================================================

# Load pre-computed statistics for normalization (mean, std, min, max) from a JSON file
# This file should have been generated by running obtain_stats.py beforehand
STATS_FILE = "stats/global_normalization_stats.json"
with open(STATS_FILE, 'r') as f:
    global_stats = json.load(f)
print(f"Loaded global statistics from {STATS_FILE}")

# ==============================================================================
# PROCESSING PIPELINE
# ==============================================================================

cont_cols   = ['x', 'y', 'z', 'r_T', 'phi', 'eta', 'n_pix', 'codex_angle']
global_cols = ['nVtx_per_event', 'nClu_per_event', 'nTrk_per_event']

means_cont  = np.array([global_stats[c]['mean'] for c in cont_cols],   dtype=np.float32)
stds_cont   = np.array([global_stats[c]['std']  for c in cont_cols],   dtype=np.float32) + 1e-8
means_glob  = np.array([global_stats[c]['mean'] for c in global_cols], dtype=np.float32)
stds_glob   = np.array([global_stats[c]['std']  for c in global_cols], dtype=np.float32) + 1e-8

def process_event(args):
    """
    Converts a single event DataFrame into a PyTorch Geometric Data object.
    """
    event_id, df_event = args
    if len(df_event) <= K_NEIGHBOURS:
        return None

    # Continuous features (normalized)
    x_cont = torch.tensor(df_event[cont_cols].values, dtype=torch.float)
    # Categorical features (module IDs for embeddings)
    x_cat = torch.tensor(df_event['module'].values, dtype=torch.long)
    # Global event-level attributes
    global_attr = torch.tensor(df_event[global_cols].iloc[0].values, dtype=torch.float).unsqueeze(0)
    # Coordinates for graph construction (k-NN in eta-phi-z space)
    coords = torch.tensor(df_event[['eta', 'phi', 'z']].values, dtype=torch.float)
    edge_index = knn_graph(coords, k=K_NEIGHBOURS, loop=False)
    # Label
    y = torch.tensor([IS_SIGNAL], dtype=torch.float)

    return Data(
        x_cont=x_cont, 
        x_cat=x_cat,
        edge_index=edge_index,
        y=y,
        global_attr=global_attr,
        event_id=torch.tensor([event_id], dtype=torch.long),
        num_nodes = x_cont.shape[0]
    )


def prepare_torch_files():

    data_type = "signal" if IS_SIGNAL else "background"
    specific_output_dir = os.path.join(OUTPUT_DIR, data_type, DEC_ID)
    os.makedirs(specific_output_dir, exist_ok=True)
    print(f"Starting processing from: {FULL_PATH} -> {LABEL}")
    print(f"Output directory: {specific_output_dir}")
    print(f"Building graphs with K={K_NEIGHBOURS} neighbors using {N_WORKERS} parallel threads...")
    print(f"Graph features:\n Event: {cont_cols} (normalized), \n Global: {global_cols} (normalized),\n Categorical: module (categorical)")

    chunk_counter = 0
    total_events = 0
    
    # Buffer to store the last event of a chunk if it's split across chunks
    leftover_df = pd.DataFrame()

    # Iterate in chunks to manage memory usage
    for chunk in uproot.iterate(FULL_PATH, VAR_NAMES, step_size="100 MB", library="pd"):

        # --- 0. HANDLE LEFTOVER FROM PREVIOUS CHUNK ---

        if not leftover_df.empty:
            chunk = pd.concat([leftover_df, chunk], ignore_index=True)
            
        # Identify the last event ID to check for completeness
        last_event_id = chunk['eventNumber'].iloc[-1]
        
        # Split chunk into complete events and the potentially incomplete last event
        is_last_event = (chunk['eventNumber'] == last_event_id)
        leftover_df = chunk[is_last_event].copy()
        df_to_process = chunk[~is_last_event].copy()

        # Skip if the entire chunk belongs to a single (still incomplete) event
        if df_to_process.empty:
            continue

        
        # --- 1. FEATURE ENGINEERING ---
        df_to_process['r_T'], df_to_process['eta'], df_to_process['phi'] = collider_system(df_to_process, x='x', y='y', z='z')
        df_to_process['codex_angle'] = compute_codex_angles(df_to_process, x='x', y='y', z='z')

        # --- 2. NORMALIZATION ---

        df_to_process[cont_cols] = (df_to_process[cont_cols].values - means_cont) / stds_cont
        df_to_process[global_cols] = (df_to_process[global_cols].values - means_glob) / stds_glob

        events = df_to_process.groupby("eventNumber")

        # --- 3. PARALLEL GRAPH GENERATION ---

        with ThreadPoolExecutor(max_workers=N_WORKERS) as executor:
            results = list(executor.map(process_event, events))

        chunk_data_list = [g for g in results if g is not None]
        total_events += len(chunk_data_list)  

        # --- 4. SAVE PROCESSED CHUNK ---
        chunk_filename = os.path.join(specific_output_dir, f"graphs_{chunk_counter}.pt")
        if chunk_data_list:
            torch.save(chunk_data_list, chunk_filename)
            print(f"Saved chunk {chunk_counter}: {len(chunk_data_list)} events (Total: {total_events})")
        else:
            print(f"Chunk {chunk_counter} contained no valid events.")

        chunk_counter += 1

    # Process the final leftover event
    if not leftover_df.empty:
        leftover_df['r_T'], leftover_df['eta'], leftover_df['phi'] = collider_system(leftover_df, x='x', y='y', z='z')
        leftover_df['codex_angle'] = compute_codex_angles(leftover_df, x='x', y='y', z='z')
        leftover_df[cont_cols]  = (leftover_df[cont_cols].values  - means_cont)  / stds_cont
        leftover_df[global_cols] = (leftover_df[global_cols].values - means_glob) / stds_glob

        last_graph = process_event((leftover_df['eventNumber'].iloc[0], leftover_df))
        if last_graph:
            torch.save([last_graph], os.path.join(specific_output_dir, f"graphs_{chunk_counter}.pt"))
            total_events += 1 
            print(f"Saved final leftover event (Total: {total_events})")

    print(f"\nProcessing completed! {total_events} graphs ready in {specific_output_dir}")

if __name__ == "__main__":
    prepare_torch_files()